<?php /* Smarty version Smarty-3.1.11, created on 2017-09-13 20:42:51
         compiled from "templates/plantillas/modulos/front-end/avisoprivacidad.tpl" */ ?>
<?php /*%%SmartyHeaderCode:81711034559b96b543f2162-27315437%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '81cbc32547acce0ada41a0d5c8416c775c31117d' => 
    array (
      0 => 'templates/plantillas/modulos/front-end/avisoprivacidad.tpl',
      1 => 1505350297,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '81711034559b96b543f2162-27315437',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.11',
  'unifunc' => 'content_59b96b54411ca6_87629196',
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_59b96b54411ca6_87629196')) {function content_59b96b54411ca6_87629196($_smarty_tpl) {?><div class="container">
<h3>AVISO LEGAL Y DE PRIVACIDAD</h3>
<h4>AVISO DE PRIVACIDAD PARA LA PROTECCIÓN DE DATOS PERSONALES</h4>
<p class="text-justify">En cumplimiento con lo establecido por la Ley Federal de Protección de Datos Personales en Posesión de Particulares, <b>Proyecto Puerta Abierta Negocios e Inversiones S. de R.L. de C.V</b> (en lo sucesivo “Rocket Card”) hacen de su conocimiento la política de privacidad y manejo de datos personales, en la que en todo momento buscarán que el tratamiento de los mismos sea legítimo, controlado e informado, a efecto de garantizar la privacidad de los mismos.</p>
<p class="text-justify">Proyecto Puerta Abierta Negocios e Inversiones será el responsable de sus datos personales, su domicilio es Calle Álvaro Obregón No. 208, Col. Fundadores, en Moroleón, Gto. México, C.P. 38810.</p>
<p class="text-justify">Los datos personales que proporcione cualquier persona física, incluyendo sin limitar, suscriptores, clientes, proveedores y/o usuarios, a Proyecto Puerta Abierta Negocios e Inversiones tendrán el uso que en forma enunciativa pero no limitativa se describe a continuación:</p>
<ul>
	<li class="text-justify">Para identificarle, ubicarle, comunicarle, contactarle, enviarle información y/o mercancía, proveer un servicio y/o mercancía, así como su transmisión a terceros por cualquier medio. El uso de los datos personales tendrá relación con el tipo de interacción que usted tiene con el Responsable, ya sea comercial, civil, mercantil o de cualquier otra naturaleza.</li>
		<p class="text-justify">Para determinados servicios como nuestros programas publicitarios y/o compra o suscripción a una revista o servicios, solicitamos también información sobre la tarjeta de crédito u otra información bancaria, que guardamos en formato encriptado en los servidores seguros de nuestro prestador de servicios. Es posible que combinemos los datos que nos proporciona el solicitante a través de su cuenta con la información procedente de otros servicios de Proyecto Puerta Abierta Negocios e Inversiones o de terceros a fin de proporcionarle una experiencia óptima y de mejorar la calidad de nuestros servicios. 	</p>
	<li class="text-justify">
		<p class="text-justify">Para determinados servicios, le ofreceremos la oportunidad de decidir si desea o no que realicemos dicha combinación de datos.</p>
		<p class="text-justify">Al visitar cualquiera de los sitios de internet de Proyecto Puerta Abierta Negocios e Inversiones, nosotros recopilamos automáticamente algunos datos personales, que luego sumamos a un conjunto para que no estén asociados a una única persona que sea identificable. Con esta información elaboramos estadísticas sobre cuántos usuarios visitaron nuestros sitios web y a qué páginas accedieron. Al recopilar esta información, aprendemos a adaptar de la mejor manera a los sitios web a nuestros visitantes. Tal y como explicamos a continuación, recopilamos esta información a través de "archivos temporales" o "web beacons".</p>
		<p class="text-justify">Archivos de registro: Los archivos temporales son archivos web del servidor (como el nombre del dominio o la dirección IP, URL, el código de respuesta http, el sitio web desde el que nos ha visitado o la fecha y duración de su visita) que se crean automáticamente cuando un usuario de Internet visita un sitio. Una vez que deje de usar nuestro sitio web, procesaremos y utilizaremos esta información sólo para permitir más conexiones, para temas de facturación, para detectar interrupciones en el equipo de telecomunicaciones, así como para detectar abusos en nuestros servicios de telecomunicaciones. Esta información se elimina inmediatamente una vez finalizada la conexión al sitio web.</p>
	</li>
	<li class="text-justify">
		<p class="text-justify">Esta información se utiliza para crear perfiles conjuntos generales de nuestra base de usuarios del sitio, y no para crear perfiles de usuario personalizados.</p>
		<p class="text-justify">Web Beacons: Algunas páginas de nuestro sitio web contienen "web beacons" (también conocidos como etiquetas de Internet, etiquetas de píxel y clear GIFs). Los web beacons permiten a terceros obtener información, como es la dirección IP del ordenador que ha descargado la página en la que aparece el beacon, la URL de la página en la que aparece el beacon, la hora en la que se produjo la visita a la página con el beacon, el tipo de navegador utilizado para visitar la página, así como la información de las cookies enviada por el tercero.</p>
	</li>
</ul>

<p class="text-justify">La temporalidad del manejo de los datos personales será indefinida a partir de la fecha en que usted los proporcionó al Responsable.</p>
<p class="text-justify">En caso que dese ejercer sus derechos de acceso, rectificación, cancelación u oposición, estos los podrán ejercer en todo momento dirigiendo su solicitud a (i) al correo electrónico <b>datospersonalesrocketcard@gmail.com</b> y/o (ii) al siguiente domicilio: Calle Álvaro Obregón No. 208, Col. Fundadores, Moroleón, Gto. México C.P. 38810 al teléfono 445 458 74 49, de Lunes a Viernes de las 10:00 a las 19:00 horas, en días hábiles, según corresponda. Para lo anterior, deberá hacernos saber fehacientemente los datos personales que usted desea sean rectificados, cancelados o revisados, así como el propósito para el cual los aportó y el nombre del Responsable a quien se los entregó y en general cumplir los requisitos mencionados en el Art. 29 de la Ley Federal de Protección de Datos Personales en Posesión de Particulares.</p>
<p class="text-justify">Proyecto Puerta Abierta Negocios e Inversiones podrá modificar el presente aviso de privacidad en cualquier tiempo y lo mantendrá siempre a disposición por este conducto para su consulta.</p>
<h4>POLÍTICA DE PRIVACIDAD</h4>
<p class="text-justify">Proyecto Puerta Abierta Negocios e Inversiones se compromete a respetar la privacidad de los usuarios que acceden al sitio web <b>www.rocketcard.com.mx</b>, por ello la información recopilada, a efecto de crear su suscripción, servicios o promociones, tal como: nombre, domicilio, teléfono, curp, dirección de Facebook y dirección electrónica se encuentra restringida, con la excepción de aquellos usuarios que participen en la sección de comentarios sobre notas publicadas en el Sitio Web y/o en los Foros. En estos espacios, con el objetivo de evitar el mal uso por personas que se refugian en el anonimato, los comentarios incluirán el nombre del titular de la suscripción con el que se participa.</p>

<ul>
	<li class="text-justify">Únicamente el usuario podrá tener acceso a sus datos personales para modificarlos de considerarlo necesario. Proyecto Puerta Abierta Negocios e Inversiones no comparte o revela ningún tipo de información, menos aún información relativa a tarjetas de crédito, números confidenciales o información relevante que pudiera causar perjuicio alguno a nuestros usuarios.
En general la información recopilada por Proyecto Puerta Abierta Negocios e Inversiones se refiere al número de visitantes y tiempo promedio que se invierte con el fin de obtener estadísticas para medir el uso y mejorar el contenido de nuestros Sitio Web. Es posible que nuestro Sitio Web proporcione enlaces a sitios de terceros, debido a que no tenemos control sobre ellos, lo invitamos a revisar las políticas de privacidad de los mismos.
	</li>
</ul>

<h3>USO DE LA INFORMACIÓN QUE RECOPILA PROYECTO PUERTA ABIERTA NEGOCIOS E INVERSIONES</h3>
<p class="text-justify"><b>A fin de poder prestarle un amplio abanico de servicios, las categorías de datos que recopilamos son las siguientes:</b>

<ul>
	<li class="text-justify">Información que usted nos proporciona: al solicitar suscripciones, servicios o promociones de Proyecto Puerta Abierta Negocios e Inversiones que requieren un proceso de registro, el solicitante deberá facilitarnos datos personales (nombre, dirección de correo electrónico y contraseña de la cuenta, por ejemplo). Para determinados servicios, como nuestros programas publicitarios y/o suscripciones solicitamos también información sobre la tarjeta de crédito u otra información bancaria, que guardamos en formato encriptado en los servidores seguros de nuestro prestador de servicio. Es posible que combinemos los datos que nos proporciona el solicitante a través de su cuenta con la información procedente de otros servicios de Proyecto Puerta Abierta Negocios e Inversiones o de terceros a fin de proporcionarle una experiencia óptima y de mejorar la calidad de nuestros servicios. Para determinados servicios, le ofreceremos la oportunidad de decidir si desea o no que realicemos dicha combinación de datos.</li>
	<li class="text-justify"><b>Cookies</b>: cuando usted visita el Sitio Web, podríamos enviar una o varias cookies (un pequeño archivo que contiene una cadena de caracteres) a su equipo mediante las que se identificará de manera exclusiva su navegador. Podríamos utilizar cookies para mejorar la calidad de nuestro servicio gracias a que almacenamos las preferencias del usuario y a que supervisamos las tendencias de comportamiento, por ejemplo, el tipo de búsquedas que realiza. Proyecto Puerta Abierta Negocios e Inversiones también podría emplear cookies en los servicios publicitarios para ayudar a anunciantes y editores a proporcionar y a gestionar anuncios en Internet. Asimismo, podríamos insertar una cookie en su navegador cuando visita un sitio web y visualiza un anuncio que pertenece a los servicios publicitarios de Proyecto Puerta Abierta Negocios e Inversiones o hace clic en él.</li>
	<li class="text-justify">Información de registro: cuando utiliza los servicios de Proyecto Puerta Abierta Negocios e Inversiones, nuestros servidores registran automáticamente la información que su navegador envía cada vez que visita un sitio web. Estos registros de servidor pueden incluir información tal como la solicitud web, la dirección de protocolo de Internet, el tipo y el idioma del navegador, la fecha y la hora de la solicitud y una o varias cookies que identifican el navegador de forma exclusiva.</li>
	<li class="text-justify"><b>Comunicaciones de usuario:</b> cuando envía mensajes de correo electrónico u otras comunicaciones a Proyecto Puerta Abierta Negocios e Inversiones, podríamos conservarlas a fin de procesar sus consultas, responder a sus peticiones y mejorar nuestros servicios.</li>
	<li class="text-justify"><b>Sitios de Proyecto Puerta Abierta Negocios e Inversiones afiliados en otros sitios: </b>ofrecemos algunos de nuestros servicios en o a través de otros sitios web. Es posible que los datos personales que usted facilite a través de estos sitios web se envíen a Proyecto Puerta Abierta Negocios e Inversiones para poder prestar el servicio. Llevaremos a cabo el tratamiento de dichos datos de conformidad con lo dispuesto en la presente Política de Privacidad. Los sitios afiliados podrían poner en práctica distintas políticas de privacidad; le recomendamos que las consulte.</li>
	<li class="text-justify"><b>Gadgets:</b> Proyecto Puerta Abierta Negocios e Inversiones podría proporcionar aplicaciones de terceros a través de sus servicios. El tratamiento de los datos recopilados por Proyecto Puerta Abierta Negocios e Inversiones al habilitar un gadget u otra aplicación se llevará a cabo de conformidad con lo dispuesto en la presente Política de Privacidad. Los datos recogidos por el proveedor de la aplicación o del gadget estarán sujetos a las políticas de privacidad de dicho proveedor.</li>
	<li class="text-justify"><b>Enlaces:</b> Proyecto Puerta Abierta Negocios e Inversiones podría ofrecer los enlaces en un formato que permita saber si se han seguido. Utilizamos esta información para mejorar la calidad de nuestra tecnología de búsqueda, así como la publicidad y el contenido personalizados. Consulte información adicional sobre enlaces y redireccionamiento de URL.</li>
	<li class="text-justify"><b>Otros sitios:</b> la presente Política de Privacidad se aplica únicamente a los servicios de Proyecto Puerta Abierta Negocios e Inversiones en el Sitio Web. No tenemos control alguno sobre los sitios web mostrados como resultados de búsqueda, sitios que incluyen aplicaciones, productos o servicios Proyecto Puerta Abierta Negocios e Inversiones, o enlaces que se incluyen en nuestros servicios. Es posible que estos sitios independientes envíen sus propias cookies u otros archivos a su equipo, recopilen datos o le soliciten que envíe datos personales.</li>
	<li class="text-justify">Proyecto Puerta Abierta Negocios e Inversiones llevará a cabo el tratamiento de los datos personales únicamente de conformidad con lo dispuesto en la presente Política de Privacidad o en las notificaciones adicionales que se incluyan en determinados servicios. Además de lo descrito anteriormente, dichos fines incluyen:
	<ul>
		<li class="text-justify">Prestar nuestros servicios a los usuarios, incluyendo la publicación de contenido y publicidad personalizados.</li>
		<li class="text-justify">Auditoría, investigación y análisis destinados a mantener, proteger y mejorar nuestros servicios.</li>
		<li class="text-justify">Asegurar el funcionamiento técnico de nuestra red.</li>
		<li class="text-justify">Proteger los derechos o la propiedad de Proyecto Puerta Abierta Negocios e Inversiones o nuestros usuarios y desarrollar nuevos servicios.</li>
		<li class="text-justify">Encontrará más información sobre el tratamiento de los datos personales en las notificaciones de privacidad adicionales de cada servicio.</li>
	</ul>
	</li>
</ul>

<h4>DIVERSAS OPCIONES RELATIVAS A LOS DATOS PERSONALES</h4>
<p class="text-justify">Cada vez que usted accede a un servicio concreto que requiere registro, solicitamos que proporcione datos personales. Si vamos a utilizar estos datos con fines distintos de aquellos para los que se hayan recopilado, le pediremos su consentimiento previo.</p>
<p class="text-justify">Si decidimos utilizar los datos personales con una finalidad distinta de la que se describe en esta Política de Privacidad o en las notificaciones específicas de cada servicio, usted tendrá la posibilidad de manifestar claramente su oposición. Proyecto Puerta Abierta Negocios e Inversiones no recopilará ni utilizará información confidencial para fines distintos de los establecidos en la presente Política o en los avisos adicionales específicos sin su consentimiento previo.</p>
<p class="text-justify">La mayoría de los navegadores están configurados para aceptar cookies, pero podrá reconfigurar su navegador para rechazar todas las cookies o para que el sistema le indique en qué momento se envía una.</p>
<p class="text-justify">Sin embargo, si las cookies están inhabilitadas, es posible que algunas características y servicios de Proyecto Puerta Abierta Negocios e Inversiones no funcionen de manera adecuada.</p>
<h4>DATOS PERSONALES</h4>
<p class="text-justify">Proyecto Puerta Abierta Negocios e Inversiones únicamente comparte los datos personales con otras empresas o particulares que no tienen relación con Proyecto Puerta Abierta Negocios e Inversiones en las siguientes circunstancias:</p>
<p class="text-justify">Cuando contamos con su consentimiento. Solicitamos que preste su consentimiento para compartir cualquier tipo de información confidencial. Facilitamos dicha información a nuestras filiales y entidades vinculadas y a otras empresas o personas de confianza para que lleven a cabo su tratamiento en nuestro nombre. Estas entidades deberán llevar a cabo el tratamiento de los datos siguiendo nuestras instrucciones y de conformidad con la presente Política de Privacidad, y deberán adoptar asimismo las medidas de confidencialidad y seguridad que consideremos oportunas. Proyecto Puerta Abierta Negocios e Inversiones considera de buena fe que el acceso, el uso, la conservación o la divulgación de esta información es razonablemente necesario para (a) cumplir con las leyes y normativas aplicables, los procedimientos judiciales o los requisitos administrativos; (b) aplicar las Condiciones del Servicio aplicables, incluyendo la investigación de las posibles infracciones que de ello se deriven; (c) detectar, impedir o abordar casos o problemas técnicos, de fraude o de seguridad por cualquier otro medio; o (d) proteger contra daños inminentes los derechos, la propiedad o la seguridad de Proyecto Puerta Abierta Negocios e Inversiones, sus usuarios o el público en la forma exigida o permitida por la ley.</p>
<p class="text-justify">Si Proyecto Puerta Abierta Negocios e Inversiones lleva a cabo una operación de fusión, adquisición o cualquier otra forma de venta de la totalidad o cualquiera de sus activos, publicaremos una notificación antes de llevar a cabo la transferencia de los datos personales y de que éstos pasen a estar sujetos a otra política de privacidad. Podríamos compartir con terceros ciertos datos globales no personales, por ejemplo, el número de usuarios que han buscado un término o el total de personas que han hecho clic en un determinado anuncio. Dicha información no le identificará de manera individual.Escríbanos a la dirección que encontrará más abajo si tiene cualquier otra pregunta relativa a la administración o utilización de los datos personales.</p>
<h4>MODOFICACIONES DE ESTA POLITICA DE PRIVACIDAD</h4>
<p class="text-justify">Tenga en cuenta que la presente Política de Privacidad podrá modificarse según se considere oportuno. No limitaremos sus derechos derivados de la presente política sin su expreso consentimiento. Esperamos que la mayoría de las modificaciones que realicemos sean menores. Publicaremos las modificaciones en esta página y, si éstas son significativas, le enviaremos el correspondiente aviso destacado, como, por ejemplo, una notificación por correo electrónico (en el caso de determinados servicios). Cada versión de la presente Política de Privacidad incorporará la fecha de entrada en vigor al principio de la página.</p>
<p class="text-justify">Si tiene alguna duda acerca de esta Política de Privacidad póngase en contacto con nosotros en cualquier momento a través de este Sitio Web o de la dirección siguiente: Calle Álvaro Obregón No. 208, Col. Fundadores, Moroleón, Gto. C.P. 38810, México.</p>



</div><?php }} ?>